name: Daily Plots

on:
  schedule:
    - cron: '15 6 * * *' # everyday 6:15 UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true


      - name: Set up GitHub credentials
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin ${{ github.ref_name }} || { echo "git fetch failed"; exit 1; }
          git checkout ${{ github.ref_name }} || { echo "git checkout failed"; exit 1; }
          git pull --rebase origin ${{ github.ref_name }} || { echo "git pull failed"; exit 1; }

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 -m pip install --upgrade pip
          pip3 install --break-system-packages pandas matplotlib

      - name: Generate plots
        run: python3 ./cmd/plot.py

      - name: Commit plots
        run: |
          git add charts/*.png
          git commit -m "🖼️ Update plots - $(date +%F)" || echo "No plot changes"
          git push || echo "Nothing to push"

