name: Daily Otomoto Scraper

on:
  schedule:
    - cron: '0 6 * * *' # everyday 6:00 UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up GitHub credentials
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin ${{ github.ref_name }} || { echo "git fetch failed"; exit 1; }
          git checkout ${{ github.ref_name }} || { echo "git checkout failed"; exit 1; }
          git pull --rebase origin ${{ github.ref_name }} || { echo "git pull failed"; exit 1; }

      - name: Download Go dependencies
        run: |
          go mod tidy || { echo "go mod tidy failed"; exit 1; }
          go mod download || { echo "go mod download failed"; exit 1; }

      - name: Run scraper
        run: |
          go run ./cmd/main.go || { echo "go run failed"; exit 1; }

      - name: Commit CSV results
        run: |
          if ls data/*.csv 1> /dev/null 2>&1; then
            git add data/*.csv
            git commit -m "📊 Daily data update - $(date +%F)" || echo "No changes to commit"
            git push || echo "Nothing to push"
          else
            echo "No CSV files to add"
          fi
